### ISSUE TITLE
Configure tree behavior

### ISSUE THREAD

**Issue by nashamri** [peterszerzo/elm-arborist#2]
Hello there,

Thanks for this cool package. This is more of a question and not an issue. I'm new to Elm and I want to create a family tree but I also want to modify the default behavior. Specifically I want to:

1. Make the tree "un-editable", I just want a static tree,
2. Remove the drag-and-drop behavior.

Also, is there an easy way to get rid of the leaf nodes? the "new child" nodes in your demo?

Again, I'm new to Elm so I might be missing something obvious here, or maybe this is just not what this package is designed to do.

Thanks again for this package :smile:

**Comment by peterszerzo** [comment]
Hi @nashamri - thank you for your interest, and sorry for the late reply!

Leaf node removal is on its way (probably within a month), and whether the tree is editable or not is up to you. Notice how in the [example](https://github.com/peterszerzo/elm-arborist/blob/master/example/Main.elm), there is a fair bit of client code creating the form that edits and removes nodes, and reacting to events. Just take that out and you have a static tree.

Removing the drag and drop behavior also sounds like a nice feature. I'll see if I can squeeze it in shortly. Some other features you can look forward to is customizing the width and the color of the links connecting the nodes. Could be helpful for styling your family tree (actual node styling is completely up to the client at the moment, as long the layout algorithm knows how wide and tall they are).

Appreciate your suggestions, let me know (e.g. Elm slack) if I can help you using the library further.

**Comment by nashamri** [comment]
Hey @peterszerzo, yeah I managed to strip the "editing" parts from the example :+1: . It would be cool to have the ability to configure the drag-and-drop and the other configurations you mentioned. Looking forward to that! :smile:

**Comment by peterszerzo** [comment]
Awesome, I'm glad it was straightforward. I'll keep you posted on progress!

**Comment by peterszerzo** [comment]
Hey @nashamri - in version `2.1.0` (just released), you can disable drag and drop using the `Arborist.Settings.dragAndDrop False` flag, and hide placeholder leaf nodes using the `Arborist.Setting.placeholderLeaves False` flag, both set when initializing your Arborist model (see http://package.elm-lang.org/packages/peterszerzo/elm-arborist/2.1.0/Arborist-Settings). Let me know if it's working the way you imagined it.

Thanks again for the suggestions, I think they're important to have implemented, and they so happen to fit in pretty cleanly into the existing structure.

**Comment by nashamri** [comment]
@peterszerzo brilliant job! thanks so much :smile: 
I'll be travelling for the next two days, hopefully I'll get some quality time with this on the plane :smile: 
I guess this issue can be closed now.
cheers!
