### ISSUE TITLE
"vertical" tree

### ISSUE THREAD

**Issue by JorisM** [peterszerzo/elm-arborist#5]
hi! first of all, we use elm-aborist as part of a prototype at work, we just upgraded from 1.x to 3.x and changes are great! we really appreciate the work you put into this. 

now my question: the trees we generate are usually pretty wide, which means there is a lot of horizontal scrolling involved. do you think there is a possibility to add a config value in order to render the tree "vertically" (sort of like a folder strucuture)?

**Comment by peterszerzo** [comment]
Hi @JorisM I am very happy to hear that it is working out for you.

We can certainly look at implementing a tree rendering in the other direction, which could be done with no changes to the core layout algorithm if you're happy with the looks below:

<img width="911" alt="screen shot 2018-05-22 at 5 33 25 pm" src="https://user-images.githubusercontent.com/6738398/40373012-4247c6fe-5de6-11e8-90d0-526333be1d77.png">

I won't be able to find the time to work on this in the next few weeks, but I am happy to provide you with some guidance if you're keen on taking a stab at it yourself.

**Comment by peterszerzo** [comment]
I am also pretty frequently online on the Elm Slack channel under peterszerzo. Holler at me there if you need anything.

**Comment by JorisM** [comment]
that looks exactly like what we need. I will ping you once a get some time to work on this, thanks
