### ISSUE TITLE
Comparison to Canopy

### ISSUE THREAD

**Issue by janwirth** [peterszerzo/elm-arborist#6]
How does arborist compare to canopy?

https://github.com/allo-media/canopy/tree/1.0.0

**Comment by peterszerzo** [comment]
Hi @FranzSkuffka - `canopy` looks like a comprehensive library that you can use to create, update and manipulate tree structures in Elm code. `arborist` is by contrast a visual tool - its methods for creating and manipulating trees are pretty sparse, and the focus is on visualizing and handling user interaction to add, remove, rearrange and edit nodes in HTML.

It could be interesting to look into using `canopy` in order not to have to reinvent the wheel inside `arborist`, though having a compact API that people can absorb quickly also has its benefits.

**Comment by peterszerzo** [comment]
@FranzSkuffka closing this issue for now - please feel free to re-open for further discussion. We can also chat on Elm Slack.
