### ISSUE TITLE
Dependency error

### ISSUE THREAD

**Issue by myh98** [peterszerzo/elm-arborist#7]
It seems that an indirect dependency "Skinney/murmur3" is not downloadable.

**Comment by peterszerzo** [comment]
Hi @myh98, thanks for flagging, I'm on it!!

**Comment by peterszerzo** [comment]
@myh98 this Skinney/murmur3 package is not available in indirect dependencies anymore: https://github.com/peterszerzo/elm-arborist/blob/master/elm.json. Are you by chance looking at an older version that still uses `elm-css`?

**Comment by peterszerzo** [comment]
Closing this as there are no issues with current versions. If there is more interest in getting an Elm 0.18-compatible version fixed, I can look into it at that point.
